import 'dart:io';

import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:go_router/go_router.dart';
import 'package:intl/intl.dart';
import 'package:open_filex/open_filex.dart';
import 'package:path_provider/path_provider.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:share_plus/share_plus.dart';
import 'package:zehnmind/config/router/app_router.dart';
import 'package:zehnmind/core/extensions/context_extensions.dart';
import 'package:zehnmind/core/i18n/translations.g.dart';
import 'package:zehnmind/core/theme/app_colors.dart';
import 'package:zehnmind/core/widgets/app_button.dart';
import 'package:zehnmind/features/auth/presentation/bloc/auth/auth_bloc.dart';
import 'package:zehnmind/features/profile/domain/entity/user_profile.dart';
import 'package:zehnmind/features/profile/presentation/bloc/profile_bloc.dart';
import 'package:zehnmind/features/profile/presentation/widget/profile_info_card.dart';

class ProfileScreen extends StatelessWidget {
  const ProfileScreen({super.key});

  Future<void> _shareContact(UserProfile p) async {
    await SharePlus.instance.share(
      ShareParams(
        text:
            'BEGIN:VCARD\n'
            'VERSION:3.0\n'
            'FN:${p.fullName}\n'
            'EMAIL:${p.email}\n'
            'TEL:${p.phone}\n'
            'END:VCARD',
        subject: p.fullName,
      ),
    );
  }

  Future<void> _exportPdf(UserProfile p) async {
    final pdf = pw.Document();
    pdf.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        build: (_) => pw.Padding(
          padding: const pw.EdgeInsets.all(40),
          child: pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Text(
                p.fullName.isEmpty ? 'Profile' : p.fullName,
                style: pw.TextStyle(
                  fontSize: 28,
                  fontWeight: pw.FontWeight.bold,
                ),
              ),
              pw.SizedBox(height: 4),
              pw.Text(
                'Zehnmind Tasks Profile',
                style: const pw.TextStyle(
                  fontSize: 12,
                  color: PdfColors.grey700,
                ),
              ),
              pw.SizedBox(height: 24),
              pw.Divider(),
              pw.SizedBox(height: 16),
              _pdfRow('Email', p.email),
              _pdfRow('Phone', p.phone),
              if (p.createdAt != null)
                _pdfRow('Joined', DateFormat.yMMMMd().format(p.createdAt!)),
              pw.Spacer(),
              pw.Text(
                'Generated by Zehnmind Tasks',
                style: const pw.TextStyle(
                  fontSize: 10,
                  color: PdfColors.grey500,
                ),
              ),
            ],
          ),
        ),
      ),
    );

    final dir = await getApplicationDocumentsDirectory();
    final file = File('${dir.path}/zehnmind_profile.pdf');
    await file.writeAsBytes(await pdf.save());
    await OpenFilex.open(file.path);
  }

  static pw.Widget _pdfRow(String label, String value) {
    return pw.Padding(
      padding: const pw.EdgeInsets.symmetric(vertical: 6),
      child: pw.Row(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.SizedBox(
            width: 80,
            child: pw.Text(
              label,
              style: const pw.TextStyle(fontSize: 12, color: PdfColors.grey700),
            ),
          ),
          pw.Expanded(
            child: pw.Text(
              value.isEmpty ? '—' : value,
              style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold),
            ),
          ),
        ],
      ),
    );
  }

  void _confirmLogout(BuildContext context) {
    showDialog<void>(
      context: context,
      builder: (ctx) => AlertDialog(
        title: Text(t.common.logout),
        content: Text(t.common.logout_confirm),
        actions: [
          TextButton(
            onPressed: () => Navigator.pop(ctx),
            child: Text(t.common.cancel),
          ),
          FilledButton(
            onPressed: () {
              Navigator.pop(ctx);
              context.read<AuthBloc>().add(const AuthEvent.logout());
            },
            child: Text(t.common.logout),
          ),
        ],
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(
          t.profile.title,
          style: context.textTheme.titleLarge?.copyWith(
            fontWeight: FontWeight.w700,
          ),
        ),
        actions: [
          IconButton(
            icon: const Icon(Icons.logout),
            onPressed: () => _confirmLogout(context),
          ),
        ],
      ),
      body: BlocBuilder<ProfileBloc, ProfileState>(
        builder: (context, state) {
          if (state.status == ProfileStatus.loading || state.profile == null) {
            return const Center(child: CircularProgressIndicator());
          }
          final p = state.profile!;
          final initial = p.fullName.isNotEmpty
              ? p.fullName[0].toUpperCase()
              : (p.email.isNotEmpty ? p.email[0].toUpperCase() : '?');
          return SingleChildScrollView(
            padding: const EdgeInsets.fromLTRB(16, 0, 16, 24),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.stretch,
              children: [
                Center(
                  child: Container(
                    margin: const EdgeInsets.symmetric(vertical: 16),
                    height: 96,
                    width: 96,
                    decoration: BoxDecoration(
                      shape: BoxShape.circle,
                      gradient: const LinearGradient(
                        colors: [AppColors.primary, AppColors.primaryDark],
                      ),
                    ),
                    alignment: Alignment.center,
                    child: Text(
                      initial,
                      style: const TextStyle(
                        color: Colors.white,
                        fontSize: 36,
                        fontWeight: FontWeight.w700,
                      ),
                    ),
                  ),
                ),
                Text(
                  p.fullName,
                  textAlign: TextAlign.center,
                  style: context.textTheme.titleLarge?.copyWith(
                    fontWeight: FontWeight.w700,
                  ),
                ),
                const SizedBox(height: 4),
                Text(
                  p.email,
                  textAlign: TextAlign.center,
                  style: const TextStyle(color: AppColors.textSecondary),
                ),
                const SizedBox(height: 24),
                ProfileInfoCard(
                  icon: Icons.person_outline,
                  label: t.profile.name,
                  value: p.fullName,
                ),
                ProfileInfoCard(
                  icon: Icons.email_outlined,
                  label: t.profile.email,
                  value: p.email,
                ),
                ProfileInfoCard(
                  icon: Icons.phone_outlined,
                  label: t.profile.phone,
                  value: p.phone,
                ),
                if (p.createdAt != null)
                  ProfileInfoCard(
                    icon: Icons.calendar_today_outlined,
                    label: t.profile.joined,
                    value: DateFormat.yMMMMd().format(p.createdAt!),
                  ),
                const SizedBox(height: 16),
                AppPrimaryButton(
                  label: t.profile.edit_profile,
                  icon: const Icon(
                    Icons.edit_outlined,
                    color: Colors.white,
                    size: 20,
                  ),
                  onPressed: () => context.push(AppRoute.editProfile),
                ),
                const SizedBox(height: 8),
                AppOutlinedButton(
                  label: t.profile.share_contact,
                  icon: const Icon(Icons.share_outlined, size: 18),
                  onPressed: () => _shareContact(p),
                ),
                const SizedBox(height: 8),
                AppOutlinedButton(
                  label: t.profile.export_pdf,
                  icon: const Icon(Icons.picture_as_pdf_outlined, size: 18),
                  onPressed: () => _exportPdf(p),
                ),
              ],
            ),
          );
        },
      ),
    );
  }
}
